package audit

import "github.com/api-fuzzer/apifuzzer/internal/core"

const (
	CategoryAuth        = "auth"
	CategoryDataExposure = "data-exposure"
	CategoryInputValidation = "input-validation"
	CategoryRateLimit   = "rate-limit"
	CategoryVersioning  = "versioning"
	CategoryErrorHandling = "error-handling"
	CategoryCORS        = "cors"
	CategorySecurityHeaders = "security-headers"
	CategoryInfoLeak    = "info-leak"
	CategoryHTTPMethods = "http-methods"
	CategoryContentType = "content-type"
)

var BuiltInRules = []*core.AuditRule{
	{
		ID:            "AUTH-001",
		Category:      CategoryAuth,
		Severity:      core.SeverityHigh,
		Title:         "Endpoint missing security definition",
		Description:   "The endpoint does not have any security requirements defined, making it potentially unauthenticated.",
		Enabled:       true,
		FixSuggestion: "Add security requirements to the endpoint or ensure global security covers this endpoint.",
	},
	{
		ID:            "AUTH-002",
		Category:      CategoryAuth,
		Severity:      core.SeverityHigh,
		Title:         "Write operation without authentication",
		Description:   "A write operation (POST/PUT/PATCH/DELETE) is not protected by authentication.",
		Enabled:       true,
		FixSuggestion: "Add security requirements to all write operations to prevent unauthorized modifications.",
	},
	{
		ID:            "AUTH-003",
		Category:      CategoryAuth,
		Severity:      core.SeverityCritical,
		Title:         "Sensitive operation (DELETE/PUT/PATCH) without authentication",
		Description:   "A sensitive operation that modifies or deletes data is not protected by authentication.",
		Enabled:       true,
		FixSuggestion: "Implement strong authentication for all sensitive operations that modify or delete data.",
	},
	{
		ID:            "AUTH-004",
		Category:      CategoryAuth,
		Severity:      core.SeverityMedium,
		Title:         "Global security does not cover all write operations",
		Description:   "Some write operations are not covered by the global security definition.",
		Enabled:       true,
		FixSuggestion: "Review global security settings and ensure all write operations are properly protected.",
	},
	{
		ID:            "DATA-001",
		Category:      CategoryDataExposure,
		Severity:      core.SeverityHigh,
		Title:         "Sensitive field exposed in response schema",
		Description:   "Response schema contains sensitive fields like password, secret, token, SSN, or credit card information.",
		Enabled:       true,
		FixSuggestion: "Remove sensitive fields from response schemas or ensure they are properly masked/encrypted.",
	},
	{
		ID:            "DATA-002",
		Category:      CategoryDataExposure,
		Severity:      core.SeverityMedium,
		Title:         "Full user object returned instead of minimal view",
		Description:   "Endpoint returns the complete user object with all fields instead of a minimal view.",
		Enabled:       true,
		FixSuggestion: "Create a separate minimal view schema for user responses that excludes sensitive or unnecessary fields.",
	},
	{
		ID:            "DATA-003",
		Category:      CategoryDataExposure,
		Severity:      core.SeverityMedium,
		Title:         "List endpoint missing pagination parameters",
		Description:   "List endpoint does not have limit/offset or similar pagination parameters, which could lead to data exposure and performance issues.",
		Enabled:       true,
		FixSuggestion: "Add pagination parameters (limit, offset, page, page_size) to all list endpoints.",
	},
	{
		ID:            "INPUT-001",
		Category:      CategoryInputValidation,
		Severity:      core.SeverityMedium,
		Title:         "Request parameter missing type constraint",
		Description:   "A request parameter does not have a schema type defined, which could lead to injection attacks.",
		Enabled:       true,
		FixSuggestion: "Define proper type constraints for all request parameters.",
	},
	{
		ID:            "INPUT-002",
		Category:      CategoryInputValidation,
		Severity:      core.SeverityLow,
		Title:         "String parameter missing maxLength constraint",
		Description:   "A string parameter does not have a maxLength constraint, potentially allowing very large inputs.",
		Enabled:       true,
		FixSuggestion: "Add reasonable maxLength constraints to all string parameters.",
	},
	{
		ID:            "INPUT-003",
		Category:      CategoryInputValidation,
		Severity:      core.SeverityLow,
		Title:         "Numeric parameter missing minimum/maximum constraints",
		Description:   "A numeric parameter does not have minimum or maximum value constraints.",
		Enabled:       true,
		FixSuggestion: "Add appropriate minimum and maximum constraints to all numeric parameters.",
	},
	{
		ID:            "INPUT-004",
		Category:      CategoryInputValidation,
		Severity:      core.SeverityHigh,
		Title:         "Request body without schema definition",
		Description:   "A request with a body does not have a schema defined, making validation impossible.",
		Enabled:       true,
		FixSuggestion: "Define proper JSON schemas for all request bodies to enable validation.",
	},
	{
		ID:            "RATE-001",
		Category:      CategoryRateLimit,
		Severity:      core.SeverityMedium,
		Title:         "Missing x-ratelimit extension in spec",
		Description:   "The OpenAPI specification does not define rate limiting using x-ratelimit extensions.",
		Enabled:       true,
		FixSuggestion: "Add x-ratelimit extensions to document rate limiting policies.",
	},
	{
		ID:            "RATE-002",
		Category:      CategoryRateLimit,
		Severity:      core.SeverityHigh,
		Title:         "High-frequency endpoint missing rate limit annotation",
		Description:   "Sensitive endpoints like login, register, or password reset do not have rate limiting defined.",
		Enabled:       true,
		FixSuggestion: "Implement rate limiting on all authentication and sensitive endpoints to prevent brute force attacks.",
	},
	{
		ID:            "VERSION-001",
		Category:      CategoryVersioning,
		Severity:      core.SeverityLow,
		Title:         "API path missing version number",
		Description:   "API paths should include a version number (e.g., /api/v1/...) for better backward compatibility.",
		Enabled:       true,
		FixSuggestion: "Add version prefixes to all API paths (e.g., /v1, /v2).",
	},
	{
		ID:            "VERSION-002",
		Category:      CategoryVersioning,
		Severity:      core.SeverityLow,
		Title:         "Deprecated endpoint missing sunset date",
		Description:   "A deprecated endpoint does not have a sunset date defined.",
		Enabled:       true,
		FixSuggestion: "Add x-sunset extension to deprecated endpoints indicating when they will be removed.",
	},
	{
		ID:            "ERROR-001",
		Category:      CategoryErrorHandling,
		Severity:      core.SeverityMedium,
		Title:         "Endpoint missing 4xx error responses",
		Description:   "Endpoint does not define any 4xx (client error) responses.",
		Enabled:       true,
		FixSuggestion: "Define appropriate 4xx responses (400, 401, 403, 404) for all endpoints.",
	},
	{
		ID:            "ERROR-002",
		Category:      CategoryErrorHandling,
		Severity:      core.SeverityMedium,
		Title:         "Endpoint missing 5xx error responses",
		Description:   "Endpoint does not define any 5xx (server error) responses.",
		Enabled:       true,
		FixSuggestion: "Define 500 response for all endpoints to document server error handling.",
	},
	{
		ID:            "ERROR-003",
		Category:      CategoryErrorHandling,
		Severity:      core.SeverityLow,
		Title:         "Error response missing error_code field",
		Description:   "Error response schema does not include an error_code field for programmatic error handling.",
		Enabled:       true,
		FixSuggestion: "Add error_code field to all error response schemas.",
	},
	{
		ID:            "ERROR-004",
		Category:      CategoryErrorHandling,
		Severity:      core.SeverityLow,
		Title:         "Error response missing message field",
		Description:   "Error response schema does not include a message field for human-readable error descriptions.",
		Enabled:       true,
		FixSuggestion: "Add message field to all error response schemas.",
	},
	{
		ID:            "DYNAUTH-001",
		Category:      CategoryAuth,
		Severity:      core.SeverityCritical,
		Title:         "Authentication bypass vulnerability",
		Description:   "Endpoint marked as requiring authentication accepts requests without authentication headers.",
		Enabled:       true,
		FixSuggestion: "Implement proper authentication checks on all protected endpoints.",
	},
	{
		ID:            "DYNAUTH-002",
		Category:      CategoryAuth,
		Severity:      core.SeverityHigh,
		Title:         "Insufficient role-based access control",
		Description:   "Endpoint requiring specific roles is accessible with lower-privileged credentials.",
		Enabled:       true,
		FixSuggestion: "Review and strengthen role-based access control mechanisms.",
	},
	{
		ID:            "DYNCORS-001",
		Category:      CategoryCORS,
		Severity:      core.SeverityHigh,
		Title:         "CORS policy allows wildcard origin",
		Description:   "Access-Control-Allow-Origin is set to wildcard (*), which is insecure for authenticated endpoints.",
		Enabled:       true,
		FixSuggestion: "Use specific origins instead of wildcard, especially for authenticated endpoints.",
	},
	{
		ID:            "DYNCORS-002",
		Category:      CategoryCORS,
		Severity:      core.SeverityHigh,
		Title:         "CORS allows credentials with wildcard origin",
		Description:   "Access-Control-Allow-Credentials is true while Access-Control-Allow-Origin is wildcard, which is prohibited by browsers.",
		Enabled:       true,
		FixSuggestion: "Either disable credentials or use specific origins instead of wildcard.",
	},
	{
		ID:            "DYNCORS-003",
		Category:      CategoryCORS,
		Severity:      core.SeverityMedium,
		Title:         "CORS policy allows all HTTP methods",
		Description:   "Access-Control-Allow-Methods is too permissive, allowing all HTTP methods.",
		Enabled:       true,
		FixSuggestion: "Restrict allowed methods to only those required by the API.",
	},
	{
		ID:            "DYNHEADER-001",
		Category:      CategorySecurityHeaders,
		Severity:      core.SeverityMedium,
		Title:         "Missing X-Content-Type-Options header",
		Description:   "Response does not include X-Content-Type-Options: nosniff header.",
		Enabled:       true,
		FixSuggestion: "Add X-Content-Type-Options: nosniff header to all responses.",
	},
	{
		ID:            "DYNHEADER-002",
		Category:      CategorySecurityHeaders,
		Severity:      core.SeverityMedium,
		Title:         "Missing Strict-Transport-Security header",
		Description:   "Response does not include HSTS (Strict-Transport-Security) header.",
		Enabled:       true,
		FixSuggestion: "Add Strict-Transport-Security header with appropriate max-age value.",
	},
	{
		ID:            "DYNHEADER-003",
		Category:      CategorySecurityHeaders,
		Severity:      core.SeverityLow,
		Title:         "Missing X-Frame-Options header",
		Description:   "Response does not include X-Frame-Options header to prevent clickjacking.",
		Enabled:       true,
		FixSuggestion: "Add X-Frame-Options: DENY or SAMEORIGIN header.",
	},
	{
		ID:            "DYNHEADER-004",
		Category:      CategorySecurityHeaders,
		Severity:      core.SeverityMedium,
		Title:         "Missing Content-Security-Policy header",
		Description:   "Response does not include Content-Security-Policy header.",
		Enabled:       true,
		FixSuggestion: "Implement a Content-Security-Policy appropriate for your application.",
	},
	{
		ID:            "DYNLEAK-001",
		Category:      CategoryInfoLeak,
		Severity:      core.SeverityHigh,
		Title:         "Stack trace leaked in error response",
		Description:   "Error response contains stack trace information that could help attackers.",
		Enabled:       true,
		FixSuggestion: "Disable stack traces in production error responses.",
	},
	{
		ID:            "DYNLEAK-002",
		Category:      CategoryInfoLeak,
		Severity:      core.SeverityMedium,
		Title:         "Internal file path leaked in response",
		Description:   "Response contains internal file system paths.",
		Enabled:       true,
		FixSuggestion: "Sanitize error messages to remove internal path information.",
	},
	{
		ID:            "DYNLEAK-003",
		Category:      CategoryInfoLeak,
		Severity:      core.SeverityHigh,
		Title:         "Database error details leaked",
		Description:   "Response contains database error details that could enable SQL injection attacks.",
		Enabled:       true,
		FixSuggestion: "Handle database errors gracefully and never expose raw database errors to clients.",
	},
	{
		ID:            "DYNLEAK-004",
		Category:      CategoryInfoLeak,
		Severity:      core.SeverityLow,
		Title:         "Framework version number leaked",
		Description:   "Response headers or body reveal framework/server version information.",
		Enabled:       true,
		FixSuggestion: "Configure server to hide version information in responses.",
	},
	{
		ID:            "DYNMETHOD-001",
		Category:      CategoryHTTPMethods,
		Severity:      core.SeverityMedium,
		Title:         "Undefined HTTP method not properly rejected",
		Description:   "Endpoint accepts HTTP methods that are not defined in the OpenAPI specification instead of returning 405 Method Not Allowed.",
		Enabled:       true,
		FixSuggestion: "Configure server to return 405 Method Not Allowed for undefined HTTP methods.",
	},
	{
		ID:            "DYNCONTENT-001",
		Category:      CategoryContentType,
		Severity:      core.SeverityMedium,
		Title:         "Wrong Content-Type not properly rejected",
		Description:   "Endpoint accepts requests with wrong Content-Type instead of returning 415 Unsupported Media Type or an appropriate error.",
		Enabled:       true,
		FixSuggestion: "Validate Content-Type header and return 415 for unsupported media types.",
	},
}

var DefaultSensitiveFields = []string{
	"password",
	"passwd",
	"pwd",
	"secret",
	"token",
	"auth_token",
	"access_token",
	"refresh_token",
	"api_key",
	"apikey",
	"private_key",
	"ssn",
	"social_security",
	"credit_card",
	"cc_number",
	"card_number",
	"cvv",
	"cvc",
	"expiry",
	"expiration",
	"birth_date",
	"dob",
	"mother_maiden",
	"driver_license",
	"passport",
	"bank_account",
	"routing_number",
	"pin",
}
